spring:
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
    profiles:
      active: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/redisTraining
      # 또는 jdbc:h2:./~/redisTraining
      driver-class-name: org.h2.Driver
      username: sa
      password:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace